name: Actualizar datos de glucosa

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # Ejecuta a medianoche, 6:00, 12:00 y 18:00 UTC diariamente
  workflow_dispatch:            # Permite ejecución manual desde GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    # Definir variables de entorno para el job (incluye los secretos)
    env:
      ABBOTT_EMAIL: ${{ secrets.ABBOTT_EMAIL }}
      ABBOTT_PASSWORD: ${{ secrets.ABBOTT_PASSWORD }}

    steps:
      - name: Checkout (rama main)
        uses: actions/checkout@v7
        with:
          ref: main
          path: main-code
          fetch-depth: 0       # Obtener todo el historial, para crear branch local

      - name: Configurar Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r main-code/requirements.txt

      - name: Ejecutar collector
        run: python main-code/collector.py

      - name: Checkout (rama data)
        uses: actions/checkout@v7
        with:
          ref: data
          path: data-branch
          fetch-depth: 0

      - name: Copiar base de datos y CSV al workspace de data
        run: |
          cp main-code/database/glucosesync.db data-branch/database/
          cp main-code/datos/glucose_history.csv data-branch/datos/

      - name: Commit y push de cambios en data
        run: |
          cd data-branch
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Añadir archivos modificados
          git add database/glucosesync.db datos/glucose_history.csv
          # Si no hay cambios, git commit retornará error, por eso usamos || true
          git commit -m "Actualiza datos de glucosa [ci skip]" || echo "Sin cambios para commitear"
          # Forzar push a la rama data
          git push origin data
